server.port: 8080
server.error.include-message: ALWAYS
server:
  servlet:
    context-path=: /api/v1

user:
  file:
    path: src/main/resources/users.txt

info:
  app:
    name: "java-sat-recruitment"
    description: "This is a simple API to create users"
    version: 1.0
